version: "3.7"

services:
  orders:
    container_name: orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: yarn start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb
      - billing
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  billing:
    container_name: billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: yarn start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - '5672:5672'

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=my-db
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - 27017:27017

volumes:
  mongodb_data:
    driver: local